-- Botanical records seed — auto-generated by: bun run export-seed
-- Run `bun run export-seed` to capture the current live DB state before any db reset.
-- Supabase CLI replays this file after every `bunx supabase db reset` (config.toml → [db.seed]).
--
-- Initial content: 10 baseline species from supabase/snippets/seed-botanical-cache.sql.
-- Replace by running: bun run export-seed

INSERT INTO
  public.cached_botanical_records (
    scientific_name,
    common_name,
    watering,
    sunlight,
    cycle,
    plant_type,
    is_toxic_to_pets,
    toxicity_notes,
    ideal_min_ph,
    ideal_max_ph,
    propagation_methods,
    is_perenual_enriched,
    is_ai_enriched
  )
VALUES
  (
    'Caladium bicolor',
    'Heart of Jesus',
    'Frequent',
    ARRAY['part_shade', 'full_shade'],
    'Perennial',
    'Bulb',
    TRUE,
    'Calcium oxalate crystals — oral and gastric irritation in cats and dogs',
    5.5,
    6.5,
    ARRAY['Division', 'Stem Cuttings'],
    FALSE,
    TRUE
  ),
  (
    'Monstera deliciosa',
    'Swiss Cheese Plant',
    'Average',
    ARRAY['part_shade'],
    'Perennial',
    'Herbaceous Perennial',
    TRUE,
    'Insoluble calcium oxalates — excessive drooling and oral irritation',
    5.5,
    7.0,
    ARRAY['Stem Cuttings', 'Air Layering', 'Division'],
    FALSE,
    TRUE
  ),
  (
    'Sansevieria trifasciata',
    'Snake Plant',
    'Minimum',
    ARRAY['full_sun', 'part_shade', 'full_shade'],
    'Perennial',
    'Herbaceous Perennial',
    TRUE,
    'Saponins — nausea and vomiting in cats and dogs',
    5.5,
    7.5,
    ARRAY['Division', 'Leaf Cuttings', 'Offset Separation'],
    FALSE,
    TRUE
  ),
  (
    'Epipremnum aureum',
    'Golden Pothos',
    'Average',
    ARRAY['part_shade', 'full_shade'],
    'Perennial',
    'Vine',
    TRUE,
    'Calcium oxalate crystals — oral and gastric irritation',
    6.0,
    6.5,
    ARRAY['Stem Cuttings', 'Division'],
    FALSE,
    TRUE
  ),
  (
    'Lavandula angustifolia',
    'English Lavender',
    'Minimum',
    ARRAY['full_sun'],
    'Perennial',
    'Herbaceous Perennial',
    FALSE,
    NULL,
    6.5,
    7.5,
    ARRAY['Seeds', 'Stem Cuttings', 'Division'],
    FALSE,
    TRUE
  ),
  (
    'Spathiphyllum wallisii',
    'Peace Lily',
    'Frequent',
    ARRAY['part_shade', 'full_shade'],
    'Perennial',
    'Herbaceous Perennial',
    TRUE,
    'Calcium oxalate crystals — toxic to cats and dogs',
    5.8,
    6.5,
    ARRAY['Division'],
    FALSE,
    TRUE
  ),
  (
    'Chlorophytum comosum',
    'Spider Plant',
    'Average',
    ARRAY['part_shade'],
    'Perennial',
    'Herbaceous Perennial',
    FALSE,
    NULL,
    6.0,
    7.0,
    ARRAY['Division', 'Offset Separation', 'Seeds'],
    FALSE,
    TRUE
  ),
  (
    'Aloe vera',
    'Aloe Vera',
    'Minimum',
    ARRAY['full_sun', 'part_shade'],
    'Perennial',
    'Succulent',
    TRUE,
    'Saponins and anthraquinones — vomiting and diarrhoea in pets',
    7.0,
    8.5,
    ARRAY['Offset Separation', 'Division'],
    FALSE,
    TRUE
  ),
  (
    'Helianthus annuus',
    'Common Sunflower',
    'Average',
    ARRAY['full_sun'],
    'Annual',
    'Annual',
    FALSE,
    NULL,
    6.0,
    7.5,
    ARRAY['Seeds'],
    FALSE,
    TRUE
  ),
  (
    'Ficus lyrata',
    'Fiddle-Leaf Fig',
    'Average',
    ARRAY['full_sun', 'part_shade'],
    'Perennial',
    'Tree',
    TRUE,
    'Proteolytic enzyme in sap — skin and oral irritation',
    6.0,
    7.0,
    ARRAY['Stem Cuttings', 'Air Layering'],
    FALSE,
    TRUE
  )
ON CONFLICT (scientific_name)
DO NOTHING;
