/**
 * Exports cached_botanical_records from the local Supabase DB to supabase/seed.sql.
 * The Supabase CLI auto-runs seed.sql after every `db reset` (config.toml → [db.seed]).
 *
 * Run before any `bunx supabase db reset` to preserve accumulated botanical data:
 *   bun run export-seed
 */

import { join } from 'node:path';

// import.meta.dir = supabase/scripts/ — one level up lands in supabase/
const SEED_PATH = join(import.meta.dir, '..', 'seed.sql');

async function findDbContainer(): Promise<string> {
  const proc = Bun.spawn(
    ['docker', 'ps', '--filter', 'name=supabase_db', '--format', '{{.Names}}'],
    {
      stderr: 'inherit',
    },
  );
  const raw = await new Response(proc.stdout).text();
  await proc.exited;

  const container = raw
    .trim()
    .split('\n')
    .map((l) => l.trim())
    .find((l) => l.startsWith('supabase_db_'));

  if (!container) {
    throw new Error("Supabase DB container not found. Is 'bunx supabase start' running?");
  }
  return container;
}

async function pgDump(container: string): Promise<string> {
  // --data-only      — skip schema DDL (migrations handle that)
  // --column-inserts — generate INSERT with explicit column names (safe against reordering)
  // --table          — restrict to just this table
  const proc = Bun.spawn(
    [
      'docker',
      'exec',
      container,
      'pg_dump',
      '-U',
      'postgres',
      '--data-only',
      '--column-inserts',
      '--table=public.cached_botanical_records',
      'postgres',
    ],
    { stderr: 'inherit' },
  );

  const output = await new Response(proc.stdout).text();
  const code = await proc.exited;

  if (code !== 0) throw new Error(`pg_dump exited with code ${code}`);
  return output;
}

const container = await findDbContainer();
console.log(`Container: ${container}`);

const dump = await pgDump(container);
const rowCount = (dump.match(/^INSERT INTO/gm) ?? []).length;

const seed = [
  '-- Auto-generated by: bun run export-seed',
  `-- ${rowCount} rows captured from cached_botanical_records.`,
  '-- Supabase CLI replays this file after every db reset (config.toml → [db.seed]).',
  '-- To refresh: bun run export-seed',
  '',
  dump,
].join('\n');

await Bun.write(SEED_PATH, seed);
console.log(`Exported ${rowCount} botanical records → supabase/seed.sql`);
